all:
	g++ -O3 -march=native ./Rocchio_Raw/src/Rocchio.cpp -o ./Rocchio_Raw/build/Rocchio
	g++ -O3 -march=native ./Rocchio_Weighted/src/Rocchio.cpp -o ./Rocchio_Weighted/build/Rocchio
	
clean:
	rm -rf ./Rocchio_Raw/build/*
	rm -rf ./Rocchio_Weighted/build/*